### ISSUE TITLE
Finish the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m2-evaluacion-intermedia-libertadpozos#1]
Good job @libertadpozos  !!!

Here you have some tips to improve the exercise:

- [x] On page load execute 'getRandomNumber' and store the returned value into a constant.
- [x] Use the stored 'randomNumber' to compare against the input value when the user clicks the button and finish the feedback logic.
- [x] Define the logic to make the counter work
- [x] Indent and avoid extra white spaces to improve readability and prevent bugs
- [x] Define a good structure of folders and files for the project
- [x] Remove unused files/folders from the project: node_modules, package-lock.json

Let me know if you have any doubts ;)

Go for it!!

**Comment by libertadpozos** [comment]
Hey, @nasivuela I think I am done :)  can you check it, please?

**Comment by nasivuela** [comment]
Cool @libertadpozos 

You still can work adding your js and CSS into folders ;) Remember suggestion at the end of lesson 1 of module 1. Here you have more improvements to keep practicing:

- [x] When executing a function there is no net to surround it with ()
- [x] Move the feedback logic to a function an execute it on each click
- [x] Move you counter logic into a function and execute it on each click
- [x] You are writing many times "feedbackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'feedbackEl'?

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting the enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

**Comment by libertadpozos** [comment]
Hi, @nasivuela I am almost done, but I am having trouble understanding the last issue. Can you explain a little bit more, please?

**Comment by nasivuela** [comment]
Sure, I mean that instead of writing the same 3 times, we could do it only once in a function, something like this:

```
const writeFeedback = msg => feedbackEl.innerHTML = msg;
```

This way you could call the function when needed with different messages.

**Comment by libertadpozos** [comment]
Hi @nasivuela!
I have finished the exercise :) 
I will continue improving it...

**Comment by nasivuela** [comment]
Super good work @libertadpozos !!

![](https://media.giphy.com/media/xSM46ernAUN3y/giphy.gif)
